LIB = libres.a

CC = arm-apple-darwin9-gcc
AR = ar
CFLAGS = -std=c99 -march=armv6 -mcpu=arm1176jzf-s

all: $(LIB)

$(LIB): res.c
	$(CC) -c $(CFLAGS) res.c
	$(AR) -ru $(LIB) res.o

clean:
	rm -rf $(LIB) res.o demo